### PR TITLE
Benchmarking SEPP

### PR DESCRIPTION
**Pull request by sjanssen2**
Due to your great work with this repo, I could relatively easily add SEPP to the list of benchmarked tools with two alternative algorithmic ideas. This benchmarking was long due and requested by https://forum.qiime2.org/t/equivalent-to-remove-pynast-failures-in-qiime2/4272/14

@nbokulich I think I was able to produce all necessary "precomputed-results" and I also ran the evaluation notebooks. What I miss is an informed conclusion about SEPP's ability to assign taxonomy based on the evaluation results. Could you maybe look through the results and come up with some concluding remarks?

Note, we only benchmark GreenGenes 13.8 (but not Silva). I heard rumours that a new version of GreenGenes might come out soon, thus it could be worth to re-do this benchmark with the newer version.

### CODE REVIEW

**Comment by sjanssen2** [comment]
@ITS: SEPP is in principle not limited to 16S, but it requires a reference alignment/phylogeny pair of decent quality to insert novel fragments into. Currently, we lack this for ITS.

**Comment by sjanssen2** [comment]
Hi @nbokulich 

1. log.tsv files are gone
2. Evaluation notebooks are added. 
3. ITS is impossible right now (see above)

As suggested, I added *novel-taxa* analysis, but looking at the results I am a bit sceptical if it can be true. Maybe I misunderstood the reference DB generation. Let me summarize what I have done such that you can point me to conceptional errors:
- for each directory in `data/novel-taxa-simulations/` like `B1-REF-L2-iter0`, there is an input `query.fasta` and a reference-db for the method `ref_seqs.fasta`.
- I took the full Greengenes 13.8 reference and sheared / pruned it down to those IDs listed in `ref_seqs.fasta`.
- Sequences from `query.fasta` are than (re-)inserted into this reduced pair of reference alignment / phylogeny via SEPP.
- for **sepp-paths**: lineage consists of the few taxonomic labels which survived the harsh shearing/pruning and thus is most of the time wrong. One could re-annotate the reduced reference via e.g. tax2tree to improve results, but for now let's just forget about sepp-paths at all.
- for **sepp-otus**: lineage is inherited from the closest OTU tip to the inserted fragment in the reduced reference and trimmed to the requested number of maximal ranks, here `2`.
My feeling is that I somewhere cheated, i.e. too much information remained in the reference and thus results are better than expected. 

Note: I cannot easily construct a new reference alignment/phylogeny from scratch, thus I need to construct them by removing things from the full reference. Reference is based on full length ribosomal sequences from Greengenes.

**Comment by nbokulich** [comment]
Thanks @sjanssen2 !

Re: novel-taxa, it sounds like maybe information is leaking through, causing sepp-otus to overperform. I have a couple questions — but my gut feeling is to just drop the novel taxa changes in this PR and investigate further. If these results are valid, this is a very exciting finding!

> My feeling is that I somewhere cheated, i.e. too much information remained in the reference and thus results are better than expected.

It seems like you did everything as intended, except that I think your approach of pruning the full reference may leave too much residual information (since the structure of the full reference phylogeny will be impacted by the query sequences that are included during alignment).

> trimmed to the requested number of maximal ranks, here 2.
Can you explain this a little more? Is this a normal part of SEPP classifier or are you adding arbitrary trimming just to this evaluation? It sounds like this could be "cheating", since your description of inheriting lineage from the closest OTU tip would result in overclassification if I understand the meaning. Novel taxa classification should resemble the other tests in every way except that specific reference and query sequences are used.

Re: mock community, a couple more changes are needed.

1. It looks like maybe you just re-ran the first plot, but not the rest of the notebook (in which all other reference dbs appear). Please re-run those cells so that only gg_13_8_otus and unite_20.11.2016_clean_fullITS are displayed
2. please uncomment unite_20.11.2016_clean_fullITS in the third cell so that these results are included in the notebook — it is not important that SEPP was not tested on ITS. After merging this notebook, these will be the public-facing results, so we want the two main dbs included.

Thanks!

**Comment by sjanssen2** [comment]
Hi @nbokulich ,

**RE: mock** I re-executed the whole notebook as requested. I did so for cross-validation and novel-taxa, as well

**RE: novel-taxa**: I misunderstood your setup and erroneously provided the classifier with the knowledge where to trim lineages. This is totally cheating!
I am using a different strategy now: Removing and pruning the reference tree/alignment to those IDs given in the simulated reference, removing all existing taxonomy labels, re-decorating them from the simulated reference taxonomy file via tax2tree and than running fragment-insertion on that.
The results integrate well better than before, but still they look quite promising for sepp-path. Your gut feeling might be right, that this novel-taxa scenario is a setup where fragment-insertion has some advantages over other tools due to the ability to integrate features in the middle of reference phylogeny branches.

What do you think?

**Comment by nbokulich** [comment]
Thanks @sjanssen2 ! Looks good. Let me review a little more and maybe get @BenKaehler to give a second opinion before I merge.

> Your gut feeling might be right, that this novel-taxa scenario is a setup where fragment-insertion has some advantages over other tools due to the ability to integrate features in the middle of reference phylogeny branches.

This does seem to support that; though sepp-paths only seems to do a little better than other methods once they are optimized:
image

So I would definitely consider using this method if I expect a high rate of "novel taxa"; but that method does not perform too well with the other evals so I would not recommend for general use based on these benchmarks.

**Comment by BenKaehler** [comment]
This PR looks ok to me, thanks @sjanssen2 and @nbokulich. The only small change I would suggest is that if `wrapper_sepp.py` is going to reside in `biocore/q2-fragment-insertion` (there appears to be a PR already - biocore/q2-fragment-insertion#43), then the links in the `taxonomy-assignment.ipynb` notebooks, and any where else they occur, should point to the `biocore` repo, rather than @sjanssen2's repo.

**Comment by nbokulich** [comment]
@sjanssen2 have you had a chance to address @BenKaehler 's comments? One those are fixed we should be ready to merge. Thanks!

**Comment by sjanssen2** [comment]
Hi @BenKaehler I'd love to follow your suggestions, but I do get issues with q2lint which complains that this script does not have the right qiime2 headers. And in fact, I don't want to make it part of the plugin. It is more a one off wrapper for this benchmark and thus quality is not the best, e.g. almost no documentation no unit tests, ...
I really don't know where to host this script best. Any suggestions? Maybe it's own repo?

**Comment by nbokulich** [comment]
@sjanssen2 is the sepp classifier code not in q2-fragment-insertion now? pls let me know... if not, a separate repo for this may be a fine spot.

**Comment by sjanssen2** [comment]
Hi @nbokulich 

SEPP code is hosted in Siavash's repository https://github.com/smirarab/sepp
References for SEPP application in the microbiome realm is at https://github.com/smirarab/sepp-refs
The q2 plugin that wraps the two above is here https://github.com/qiime2/q2-fragment-insertion
Classifier code is here https://github.com/qiime2/q2-fragment-insertion/blob/0c29d5af452f38fb780066cf00f18cc38d03d604/q2_fragment_insertion/_insertion.py#L196 (exposed to qiime2 users) and https://github.com/qiime2/q2-fragment-insertion/blob/0c29d5af452f38fb780066cf00f18cc38d03d604/q2_fragment_insertion/_insertion.py#L191 (not exposed yet, due to missing evaluation).

For a fair comparison within your cool framework, it is also necessary to subset the given reference, based on Greengenes but not identical, (=sepp-ref) as you did. But this code is only needed for evaluation. It is all wrapped up in the single file https://github.com/sjanssen2/q2-fragment-insertion/blob/tax-credit/tax-credit/wrapper_sepp.py which shall not become part of the productive q2 plugin codebase, since it is not and shall not become part of qiime2. 

Yes, we might want to put it into its own repo, or maybe as a support file either into tax-credit or tax-credit-data, since it is integral part of the evaluation.

Best,
Stefan

**Comment by nbokulich** [comment]
Thanks @sjanssen2 ! Sounds good, moving `https://github.com/sjanssen2/q2-fragment-insertion/blob/tax-credit/tax-credit/wrapper_sepp.py` to its own repo sounds fine. Pls just update the paths and commands in the notebooks in your PR and let me know when it is ready and we can merge.

**Comment by sjanssen2** [comment]
@nbokulich it's done now. New repo is https://github.com/sjanssen2/tax-credit_fragment-insertion containing only the wrapper script and URLs in the notebooks are now linking to this new resource

**Comment by sjanssen2** [comment]
:+1:

**Pull request merged**
